
## Getting and Cleaning Data Project

Yuchen Cindy Zhou

### Description

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

You should create one R script called run_analysis.R that does the following.

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

## Get the data

Download the data from source website and set working directory, unzip the file in the folder UCI HAR Dataset.



## Reading data from targeted files

#### 1. Get the big picture of the structure of the data that will be used

#### 2. Read the data from the files 


#### 3. The properties of above variables

## Merges the two datasets to create one dataset

#### 1. Concatenate the data tables by rows


#### 2. set names to variables


#### 3. Merge columns to get the data frame for all data


## Extracts only the measurements on the mean and standard deviation for each measurement

#### 1. Taken names of Features with "mean()" or "std()"


#### 2. Subset the data frame Data by seleted names of Features


#### 3. Check the structures of the data frame data

 
## Use descriptive activity names to name the activities in the dataset

#### 1. Read descriptive activity names from "activity_labels.txt"

#### 2. factorize variable activity in dataframe data using descriptive names

## Appropiately labels the dataset with descriptive variable names
In the former part, variables activity and subject and names of the activities have been labelled using descriptive names.In this part, Names of Feteatures will labelled using descriptive variable names.

prefix t is replaced by time
Acc is replaced by Accelerometer
Gyro is replaced by Gyroscope
prefix f is replaced by frequency
Mag is replaced by Magnitude
BodyBody is replaced by Body





